### ISSUE TITLE
Some notification badges  not showing

### ISSUE THREAD

**Issue by Ticklezz** [icedman/anino-dock#2]
Icon shaking when clicking to open any app. Also the notifications never appear. I selected and badge and never see on the app when a notification appears.

**Comment by icedman** [comment]
Please state the app notifications that don't show on the icons.
Notifications that are captured by d2dl and anino are only the ones that the gnome-shell sees.

**Comment by icedman** [comment]
shaking ... could you be meaning the bounce animation?

**Comment by Ticklezz** [comment]
> shaking ... could you be meaning the bounce animation?

No when you click it will shake while doing the bouncing animation.

**Comment by Ticklezz** [comment]
> Please state the app notifications that don't show on the icons. Notifications that are captured by d2dl and anino are only the ones that the gnome-shell sees.

For instance if a torrent finishes  there is no notification badge.

**Comment by icedman** [comment]
> > Please state the app notifications that don't show on the icons. Notifications that are captured by d2dl and anino are only the ones that the gnome-shell sees.
> 
> For instance if a torrent finishes there is no notification badge.

Not all app notifications are detected by the gnome-shell. If the notification is not displayed on the top panel (center pop-up when you click the date/time), this extension can't see it as well.

**Comment by icedman** [comment]
Please separate bug reports for easier tracking.

**Comment by Ticklezz** [comment]
> > > Please state the app notifications that don't show on the icons. Notifications that are captured by d2dl and anino are only the ones that the gnome-shell sees.
> > 
> > 
> > For instance if a torrent finishes there is no notification badge.
> 
> Not all app notifications are detected by the gnome-shell. If the notification is not displayed on the top panel (center pop-up when you click the date/time), this extension can't see it as well.

The app in question showed this in the dash2dock lite extension.

**Comment by icedman** [comment]
Anino and D2DL still share the same code regarding notification badges. What app are you using so I can try to investigate?
Do other badges still show for you (example Chrome, Extensions, Console apps)?

**Comment by Ticklezz** [comment]
> Anino and D2DL still share the same code regarding notification badges. What app are you using so I can try to investigate? Do other badges still show for you (example Chrome, Extensions, Console apps)?

qbittorrent.

**Comment by icedman** [comment]
> qbittorrent.

Looks like this is QT based - best with KDE :) and probably not so much with gnome
